### ISSUE TITLE
Compatibility request

### ISSUE THREAD

**Issue by yocmen** [laravel-enso/Versioning#1]
feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
* [ x] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description
Please can we get this package compatible with Laravel 5.1?

Thanks in advance.

**Comment by aocneanu** [comment]
It should be compatible with 5.1, but I don't have the setup to test it. The only limitation is the `require L5.6` in composer.json.

Just copy by hand the trait in a local project with L5.1, under the `App\Traits` folder, update the namespace and you should be good to go.

And if it works and you can use it, don't forget to support the package by starring it ;)
