### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'versionable_id' cannot be null (SQL: insert into `versionings` (`version`, `versionable_id`, `versionable_type`, `updated_at`, `created_at`) values (1, , App\\Models\\ModelName, 2020-01-22 05:37:34, 2020-01-22 05:37:34))

### ISSUE THREAD

**Issue by muhammedkamel** [laravel-enso/versioning#15]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I am trying to use this package to apply optimistic locking but I face this problem when I trying to retrieve a model that uses `Versionable` trait.

```php
ModelName::where('id', $value)->select('version_id', 'name')->first();
```

Trace:
```js
{
    "file": "$PROJECT_NAME/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php",
    "line": 252,
    "function": "save",
    "class": "Illuminate\\Database\\Eloquent\\Model",
    "type": "->"
},
{
    "file": "$PROJECT_NAME/vendor/laravel-enso/versioning/src/app/Traits/Versionable.php",
    "line": 94,
    "function": "save",
    "class": "Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany",
    "type": "->"
},
{
    "file": "$PROJECT_NAME/vendor/laravel-enso/versioning/src/app/Traits/Versionable.php",
    "line": 22,
    "function": "startVersioning",
    "class": "App\\Models\\Listings",
    "type": "->"
}
```

### Steps to Reproduce
1. Install Laravel.
2. Install the package.
3. Create a model and use the `Versionable` trait in it.
4. Run a query like this `ModelName::where('id', $value)->select('version_id', 'name')->first();` selecting some fields.
5. It will throw an exception.
> **Note**: When you remove the **`Versionable`** trait from the model it returns the expected result without exceptions.

### Expected behavior
It should returns:
```js
{
  "version_id": "2",
  "name": "hamada"
}
```

### Actual behavior
```sql
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'versionable_id' cannot be null (SQL: insert into `versionings` (`version`, `versionable_id`, `versionable_type`, `updated_at`, `created_at`) values (1, , App\\Models\\ModelName, 2020-01-22 05:37:34, 2020-01-22 05:37:34))
```

**Comment by aocneanu** [comment]
Versionable creates a [one to many polymorphic relation](https://laravel.com/docs/6.x/eloquent-relationships#one-to-many-polymorphic-relations) to your model. For this to work the model class and id is needed on each version creation. Add the `id` in your query

`ModelName::where('id', $value)->select('id', 'version_id', 'name')->first();`

or maybe

ModelName::find('id');
