### ISSUE TITLE
arrow functions causing issues.

### ISSUE THREAD

**Issue by denjaland** [laravel-enso/versioning#17]
Hi guys,

You might want to have a quick look at my issue https://github.com/laravel/framework/issues/32159#issuecomment-605888470 as I noticed you are using the new arrow function syntax as well.

When combining two traits that register event handlers to the same eloquent event using arrow functions, you'll run into this issue as well, which directly impacts your packages.

Thought I'd share it with you so you may decide to temporarily revert the upgraded syntax ;-)

**Comment by aocneanu** [comment]
As you can see all of our short closures used in listeneres return methods that return nothing (null).

We hit this problem early when upgrading to php 7.4 and since then we avoided it.
