### ISSUE TITLE
Incorrect balance during race condition

### ISSUE THREAD

**Issue by panadol007** [laravel-enso/versioning#18]
This is  a **bug**.

### Prerequisites
* [Y] Are you running the latest version?
* [Y] Are you reporting to the correct repository?
* [Y] Did you check the documentation?
* [Y] Did you perform a cursory search?

### Description
Referring to following link example: 
https://medium.com/@aslrousta/pessimistic-vs-optimistic-locking-in-laravel-264ec0b1ba2
We attempt to create multiple concurrent request to deduct payment from 1 account, after implement the package, the result are same, when there is race condition, the database value are still having wrong calculation. 

### Steps to Reproduce
Mechanism to implement the package: 
`composer require laravel-enso/versioning:1.4.3`
Composer updated my laravel from 7.12.0 to 7.17.2 automatically
Amend enso migration file to big integer + unsigned 
`php artisan migrate `

In account model: 
> use LaravelEnso\Versioning\App\Traits\Versionable;
> 
> class Account extends Model 
> {
>    use Versionable;

Our configurations as below: 
1. Apache to handle 600 connections
2. 1 x php artisan serve running 
3. 4 x php artisan queue:work
4. jMeter fire 25 threads [users] x 2 loops in 1 second
5. **Update account model from another user model**

Laravel Version: 7.17.2
Queue System: Redis 
Enso/versioning: 1.4.3
Database: MySQL 8.0
OS: Mac OS 10.15.5

We amended your migration file to: 
        Schema::create('versionings', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned();

            $table->string('versionable_type');
            $table->unsignedBigInteger('versionable_id');

            $table->bigInteger('version')->unsigned();

            $table->timestamps();

            $table->unique(['versionable_type', 'versionable_id']);
        });

Unsigned and BigInteger is needed as 1 account will be used forever

### Expected behavior
1. versionings table updated_at shows latest time after our test
2. account model balance_amount shall show correct amount in race condition

### Actual behavior
1. Wrong balance_amount in account model

**Comment by raftx24** [comment]
Can you give your test script? how do you update your model?

**Comment by panadol007** [comment]
Hi Raftx24, 

Thank you for your reply.
In my scenario, to be precise: 
1 User has multiple Companies 
1 Company has multiple Accounts
ALSO 1 Company has multiple Users

The update process is: 
        while ($outstanding > 0) {
            $oldestTopup = $this->topups()->where('balanceamount', '>', 0)->orderBy('created_at')->first();
            if (is_null($oldestTopup))
                return false;

            if ($oldestTopup->balanceamount >= $outstanding) {
                // Log::info("Enough balance to deduct");
                $oldestTopup->balanceamount -= $outstanding; 
                $outstanding = 0;
            }
            else {
                $outstanding -= $oldestTopup->balanceamount; 
                $oldestTopup->balanceamount = 0;
            }
            $oldestTopup->save();
        }

I implemented **versioning** trait in Account model 
But when try  to implement **versioning** trait in Company model, it produce error saying no relationship between \App\versionings and \App\Company

**Comment by raftx24** [comment]
* For the race condition problem, you need to use `lockForUpdate` or something similar(you can look at [pessimistic-locking](https://laravel.com/docs/7.x/queries#pessimistic-locking)) because this package cannot control concurrency in this way!
* For the second issue, please give me the classes(with relation methods) and exception trace
