### ISSUE TITLE
Feature: Use polymorphism?

### ISSUE THREAD

**Issue by bloggervista** [laravel-enso/Versioning#3]
Sometime I may just want versioning data to single table so that it will be data driven approach.

Benefits:
1. Can easily enable or disable Versioning based on whether model uses trait or not
2. Helps to clean many tables as every table is free from version column

Down Side:
1. One more query

**Comment by aocneanu** [comment]
The new architecture is implemented in v1.1.x. If you find any problems let me know.

**Comment by bloggervista** [comment]
Thanks

**Comment by bloggervista** [comment]
@aocneanu why not add .DS_STORE to gitignore file?

**Comment by aocneanu** [comment]
I should. You can make a(nother) contribution, also :)
