### ISSUE TITLE
Being able to temporarily disable the trait

### ISSUE THREAD

**Issue by denjaland** [laravel-enso/versioning#6]
This is  a **feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
Hi,

In our existing migrations, we have some data that we create, for instance the "default user" account.  Since we now have added the trait to the User model, the trait comes in actions, and wants to save the versionings table, which at this time does not exist yet, because the migration for the laravel-enso/versioning comes later in the migrations.

Hence, doing a migrate:fresh now basically does no longer work because it crashes when creating models and saving them to the database.

I would like a way to temporarily disable the trait in the database migrations.  Would this be a nice feature?

**Comment by aocneanu** [comment]
I guess that we can change the name of the migration to make sure it's prior everything else and then make sure that `php artisan enso:upgrade` will update the migration name for existing projects.

**Comment by denjaland** [comment]
Sounds great.  Meanwhile, we moved our default data providers away feom migrations into their separate command that we now run after migratuons...

Thanks!

**Comment by aocneanu** [comment]
fixed in c8207741f99d6f9f47b51b9197766f5901a3cf67
