### ISSUE TITLE
Error when saving a versioned model through an associate operation

### ISSUE THREAD

**Issue by denjaland** [laravel-enso/versioning#8]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
Updating a versionable model causes for an error because he wants to persist the version into the database

### Steps to Reproduce
Consider the following code

```php
class MyController {

    public function SomeAction(Request $request,MyModel $myModel) {

        $someRelatedModel = SomeRelatedModel::find(1);

        // setting the version attribute from the client to trigger Versionable checks
        $item->version = $request->get('version');

        $item->relation()->associate($someRelatedModel);
        $item->save();

    }

}
```

This returns the following error:

```
Column not found: 1054 Unknown column 'version' in 'field list' (SQL: update `items` set `relation_id` = 1, `version` = ?, `items`.`updated_at` = 2019-08-21 15:12:40 where `id` = 1)
````

### Expected behavior
Should correctly save the `$item``

### Actual behavior
Error is thrown.  I believe because you are adding `version` to the `$this->attributes` in the model.  I don't think Eloquent likes it...

**Comment by aocneanu** [comment]
I cannot reproduce.

I added `Versionable` on the Role model and associated a user then followed your code.

I'm guessing `$item` is in fact `$myModel`.

**Comment by denjaland** [comment]
Hi,

Did you set the ->version attribute in your code?
I see that in your new version you no longer work with the attribute, but how do we set it then to make sure you validate it properly upon saving?

**Comment by aocneanu** [comment]
Yes I did. The tests were on 1.2.6, the same version you're using.

On the new version you can check version with the public helper `checkVersion`

`$model->checkVersion($request->get('version')`

That's working on the old version as well.

**Comment by denjaland** [comment]
I seriously had to revert back to 1.2.6 for the time being.

Can you confirm that `$item->version = $request->get('version');` is still what we are supposed to do to trigger the validation?

I don't see anything in your trait anymore setting that variable, so won't Eloquent just treat it as a regular attribute, and try saving it, hence the error I'm getting?

**Comment by aocneanu** [comment]
>On the new version you can check version with the public helper checkVersion
$model->checkVersion($request->get('version')
That's working on the old version as well.

**Comment by denjaland** [comment]
Yes, but that's not enough, is it?  I need to be able to set the version so that your trait will fail?
Now, if we do this:

```php
$model = Model::find($id);
// some business logic here...
$model->save();
```

That save operation has to throw an exception when between my find operation and the save, another process saved the model.

In the old version, we dit this by doing this:

```php
$model= Model::find($id);
// some business logic here

$model->version = request()->get('version');
$model->save();
```

What you are suggesting, is the following:
```php
$model= Model::find($id);
// some business logic here

$model->checkVersion(request()->get('version')); // this wil fail if the retrieved model mismatches the request id...


$model->save();
```

however if in this case there is another process updating the model between my ->checkVersion() and the save, it'll let the operation through.

**Comment by aocneanu** [comment]
Seems that you are right! Don't use the latest version, I'll look into it.

**Comment by denjaland** [comment]
yep - thanks a lot for that.  I'd dig into it to helo you, but I'm on some serious deadlines, hence my somewhat later response.

thanks for your great efforts though!
