### ISSUE TITLE
Trait complains about inserting an empty id which he shouldn't be inserting

### ISSUE THREAD

**Issue by denjaland** [laravel-enso/versioning#9]
This is  a **bug**.

### Prerequisites
* [ ] Are you running the latest version? --> version **1.2.6**
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
Sorry to spam you, but I'm running into yet another strange issue.
This is the code that we are running:

```php
PendingCharge::firstOrCreate([])
    ->invoice_elements()
    ->value(DB::raw("SUM(amount + tax_amount)"));
```

What it does, is that it requires an object of model `PendingCharge`(it's globally scoped, so you only get one for the current _tenant_).
If it doesn't exist, it creates one (`firstOrCreate`).

Then for that object, it fetches the QueryBuilder for the relation `invoice_elements`.

We need the sum of that collection for two fields combined.

Now for some reason, this is raising the error 

```
SQLSTATE[23000]: Integrity constraint violation: 1048 **Column 'versionable_id' cannot be null** (SQL: insert into `versionings` (`version`, `versionable_id`, `versionable_type`, `updated_at`, `created_at`) values (1, ?, invoice_element, 2019-08-24 23:54:42, 2019-08-24 23:54:42))
```

It seems it wants to start versioning on an element that is not currently persisted in the database (invoice_element)

It must have something to do with the ->value() method already emitting an event that you hook into that I didn't expect to be honest.

I currently worked around this by doing two calls to take ->sum('amount') and ->sum('tax_amount') seperately so we can return them, but thought I'd raise this anyhow, so you have track of what we run into :-)

thanks
### Steps to Reproduce
See Description

### Expected behavior
Not having the error

### Actual behavior
An exception

**Comment by aocneanu** [comment]
@denjaland  reopen if the new version still does this.
